### ISSUE TITLE
Evalution dataset

### ISSUE THREAD

**Issue by Sevati** [elimkwan/Python-Bilateral-Guided-Upsampling#1]
Hello, could you please provide the transfrom recipes dataset, please? Thank you

**Comment by elimkwan** [comment]
Hi, thanks for your interest in the project. However, when the project was implemented, there was very limited time. Hence, the evaluation is done on a single image for each operator. The images used in the Local Laplacian and Tone Mapping Operators experiments are from the original research (Jiawen Chen et al. “Bilateral guided upsampling”) and [sIBL](http://www.hdrlabs.com/sibl/archive.html). The other image was taken by myself. Feel free to look at the report for more details.
